services:
  postgres:
    image: postgres:17
    container_name: planningsup_db
    env_file: db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - planningsup_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    image: ghcr.io/kernoeb/planningsup/planning:refactor-elysia-postgresql
    container_name: planningsup_webapp
    env_file: webapp.env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - '31021:20000'
    networks:
      - planningsup_network

networks:
  planningsup_network:
    driver: bridge
